### ISSUE TITLE
RPC need an absurd amount of CPU/GPU usage from PyTorch

### ISSUE THREAD

**Issue by Scarlaid** [ZANdewanai/Genshin-Impact-Rich-Presence#11]
What purpose did an RPC need PyTorch for?
Anyway, installing from the `requirements.txt` file doesn't install pytorch with CUDA 118 or CUDA 121, given the picture

Title should speak for the image below
![image](https://github.com/ZANdewanai/Genshin-Impact-Rich-Presence/assets/90851437/febba5ad-5ad1-415f-bb48-0e8e50e878c4)

**Comment by ZANdewanai** [comment]
pytorch was added by the previous person that remade this rich presence, its used to make the processing speed way faster by using your gpu but since your pc doesnt have a gpu capable of using it or by some other weird issue on your end it isnt detecting it so it just defaults to cpu 

here's how mine looks, uses around 2gb ram or rather allocates that much as you see in process explorer, in task manager is just 584mb ish

(my monitors have different screen size, left is 1080p and right is 1440p so thats why its cut on the right)

![image](https://github.com/ZANdewanai/Genshin-Impact-Rich-Presence/assets/68141931/f0609c8d-68b5-44df-9a78-8cb24e6c501a)

![image](https://github.com/ZANdewanai/Genshin-Impact-Rich-Presence/assets/68141931/06de7028-49b6-4e58-b78a-99400fdf3de6)
